### ISSUE TITLE
Ambient Temperature?

### ISSUE THREAD

**Issue by Galapagon** [sebirdman/hass_traeger#10]
Where is this pulling data from? Mine is reading 60F, but nothing in my area is 60F. Grill is 225, outside is 30.

**Comment by sebirdman** [comment]
@Galapagon great question, i have no earthly clue honestly. it's in the API and i'm thinking it's somewhere inside the grill.

**Comment by Velines** [comment]
I think the readings are wrong because the grill is running. I did not notice a significant difference when it the grill was not yet firing. In my understanding the ambient temperature is only used to modify the ignition process, as mine often says "cold-weather start up" or something similiar.

**Comment by sebirdman** [comment]
we should figure out at some point when it goes into "cold weather startup" mode. then we can get rid of this temperature and instead just have a sensor that says if it'll be a cold weather start.

**Comment by njobrien1006** [comment]
I think amb. was 60F this morning and it went Cold Weather Start. Personally, as the grill sits in the garage full-time, I like having a constant readback of my garage temperature.

**Comment by sebirdman** [comment]
I don't think the ambient sensor goes below 60

The sensor we use for the grill itself seems more accurate. 

Right now my outdoor temp from my weather station is 57.2

The grill temp says it's 56

Ambient temp reads 65

**Comment by sebirdman** [comment]
I think we've answered the initial question here. It's not a great sensor, but it does a thing.
