### ISSUE TITLE
Remove cool from climate?

### ISSUE THREAD

**Issue by borski** [sebirdman/hass_traeger#12]
I noticed in #6 that you decided to keep the “cool” feature of the climate entity and even added it as an additional “shut down” procedure, but why have the cool at all? 

Is there a way to simply get rid of the cool functionality entirely and make it a heat-only heater?

**Comment by stephenpapierski** [comment]
The Traeger app itself shows when the grill is in the cool down mode and sends an alert when the grill has finish cooling down. I thought it would be nice to have a distinction between "cooling down" and "off" so you could trigger something in HA when the grill has cooled and and is ready to be covered. 

Can the cool functionality be removed? Yes. So I guess it's a matter of preference.

**Comment by borski** [comment]
That makes perfect sense. Does it actually switch into cool mode when the traeger is cooling down, and then off when it’s off? If so, that’s fantastic, actually.

On Feb 16, 2021, at 7:33 PM, Stephen Papierski <notifications@github.com> wrote:

﻿

The Traeger app itself shows when the grill is in the cool down mode and sends an alert when the grill has finish cooling down. I thought it would be nice to have a distinction between "cooling down" and "off" so you could trigger something in HA when the grill has cooled and and is ready to be covered.

Can the cool functionality be removed? Yes. So I guess it's a matter of preference.

**Comment by stephenpapierski** [comment]
Yep, that's exactly what it does.

**Comment by borski** [comment]
OK then, I'd recommend updating the docs at least, but now it makes sense! I'll close the issue.
