### ISSUE TITLE
COnfiguration possible outside of HA UI?

### ISSUE THREAD

**Issue by benkokes** [sebirdman/hass_traeger#15]
I am trying to run this on a Docker container, under HACS.  The repo adds just fine, but it does not show any kind of configuration setting. Is there a file somewhere that stores that info, I can just manually edit?

Thanks!

![image](https://user-images.githubusercontent.com/4460667/111092843-74b77980-84f4-11eb-9318-5c669026207f.png)

**Comment by sebirdman** [comment]
@benkokes you should be able to add it to the integration page, just like any other integration!

**Comment by benkokes** [comment]
Hi Stephen,

From your pictures, I see how the progression should go. I think that my version of docker (its running on my Synology NAS) and thus the Home Assistant might be more stripped down than the one you are using. So I am just trying to see how to configure it from files/command line to try and see if it will just talk to my Traeger.

Thanks for the response, as I appreciate that its not a ghost project!
Cheers,
-Ben
________________________________

**Comment by doctorkb** [comment]
> you should be able to add it to the integration page, just like any other integration!

when I try to do this, it fails -- this appears on the console:
`2021-12-01 15:50:39 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration traeger: No module named 'paho'
`

I've tried installing paho-mqtt ("pip3 install paho-mqtt") but that didn't help.

**Comment by sebirdman** [comment]
i'm not sure if this ever went anywhere, as far as i can tell using the UI configuration is the way home assistant is going going to close this
