### ISSUE TITLE
2021.6.3  Setup failed for traeger: Integration not found.

### ISSUE THREAD

**Issue by benschwartz42** [sebirdman/hass_traeger#17]
Started seeing this error when upgraded to core-2021.6.3

Logger: homeassistant.setup
Source: setup.py:172
First occurred: 9:20:47 AM (1 occurrences)
Last logged: 9:20:47 AM

Setup failed for traeger: Integration not found.

**Comment by sebirdman** [comment]
I've pushed a new update, can you take a look?

**Comment by notmayo** [comment]
Not to hijack from the OP but this is loading again for me.

**Comment by benschwartz42** [comment]
Looks like error went away. Thanks
