### ISSUE TITLE
Error setting up entry / Timeout error fetching information from AWS

### ISSUE THREAD

**Issue by AaronAutomation** [sebirdman/hass_traeger#18]
Integration no longer working for me. It had been flaky in the past but I was able to manually re-add it to get it going. It's too bad because I really love this work and being able to trend my grill temps. 

Entry Error:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/traeger/__init__.py", line 49, in async_setup_entry
    await client.start()
  File "/config/custom_components/traeger/traeger.py", line 224, in start
    await self.update_grills()
  File "/config/custom_components/traeger/traeger.py", line 119, in update_grills
    self.grills = json["things"]
TypeError: 'NoneType' object is not subscriptable

AWS Timeout:
Timeout error fetching information from https://cognito-idp.us-west-2.amazonaws.com/ -
Timeout error fetching information from https://1ywgyc65d1.execute-api.us-west-2.amazonaws.com/prod/users/self -
Timeout error fetching information from https://1ywgyc65d1.execute-api.us-west-2.amazonaws.com/prod/mqtt-connections -

**Comment by sebirdman** [comment]
@AaronAutomation give the latest a shot. Lots of good fixes in the latest build.

**Comment by sebirdman** [comment]
i'm closing this to track with https://github.com/sebirdman/hass_traeger/issues/20
