### ISSUE TITLE
Setting for temperature units

### ISSUE THREAD

**Issue by doctorkb** [sebirdman/hass_traeger#28]
### User story

**As a user** outside the United States who uses degrees Fahrenheit to cook but degrees Celsius for weather, 
**I can** select temperature units for the display / setting cards 
**so that** they can differ from the ones used in other parts of the Home Assistant interface and match the ones used in the Traeger app.

**Comment by njobrien1006** [comment]
[https://community.home-assistant.io/t/override-system-wide-settings-for-temperature/193140/24](url)
[https://community.home-assistant.io/t/allow-unit-system-to-be-overridden-on-a-per-sensor-basis/112766](url)

I switched my grill to C and continued to get F in HA. Switched HA to C and everything showed C correctly. Issue is related to trying to split C & F within HA.

IMO this as a HA issue/request. Not an issue of the integration.

**Comment by doctorkb** [comment]
It may be, but I thought it was how the integration was dealing with the display of the value.  I'll admit I'm not familiar with how HA structures these things.

It seems odd that an integration can't force certain units if it chooses to override HA's default.

**Comment by njobrien1006** [comment]
The API is sending a C or F value as defined by the grill's set unit. I attempted to remove the unit from my HA but, it seems to be required for the climate entity.

Since your HA instance is set for C it converts the F your grill is providing to C based on your FrontEnd settings.

Based on the links provided, I don't know that there is an easy fix for your desired operation.

**Comment by sebirdman** [comment]
I agree with @njobrien1006 here. I think you should open a request in HA

**Comment by sebirdman** [comment]
@doctorkb looks like this is done in HA now! https://www.home-assistant.io/blog/2022/04/06/release-20224/#adjusting-unit-of-measurement-for-sensors

**Comment by fatbob01** [comment]
@sebirdman most temperature sensors in HA support this change, but it doesn't seem to be available for Traeger for some reason...
