### ISSUE TITLE
MQTT Server "Connection failed"

### ISSUE THREAD

**Issue by njobrien1006** [sebirdman/hass_traeger#33]
## Version of the custom_component 

Latest custom_component 
Latest HA

## Configuration

```json

{"thingName":"xxxxxxxxxxxxx","jobs":[{"jobId":"Link_Combined_Timberline850_Manifest_Txxxx_Config_xxxxx","thingName":"xxxxxxxxxxxxx","currentStatus":{"status":"SUCCEEDED","timestamp":1614544310},"isFinished":true,"isInProgress":false}],"status":{"ambient":60,"connected":true,"cook_id":"","cook_timer_complete":0,"cook_timer_end":0,"cook_timer_start":0,"current_cycle":0,"current_step":0,"errors":0,"grill":34,"in_custom":0,"keepwarm":0,"pellet_level":60,"probe":0,"probe_alarm_fired":0,"probe_con":0,"probe_set":0,"real_time":0,"server_status":1,"set":165,"smoke":0,"sys_timer_complete":1,"sys_timer_end":0,"sys_timer_start":0,"system_status":2,"time":1640747264,"units":1,"acc":[{"uuid":"p0","channel":"p0","type":"probe","con":0,"probe":{"get_temp":0,"set_temp":0,"alarm_fired":0}}]},"features":{"cold_smoke_enabled":0,"grill_mode_enabled":0,"open_loop_mode_enabled":0,"pellet_sensor_connected":1,"pellet_sensor_enabled":1,"super_smoke_enabled":1,"time":1640743755},"limits":{"max_grill_temp":500},"settings":{"config_version":"xxxxx","device_type_id":xxxx,"feature":0,"fw_build_num":"xxxxxxxxxxx","fw_version":"Txxxx","language":0,"rssi":-56,"speaker":1,"ssid":"xxxx","time":1640743754,"units":1},"usage":{},"custom_cook":{"cook_cycles":[{"cycle_name":"Chicken Challenge","populated":1,"num_steps":1,"units":1,"slot_num":0,"steps":[{"probe_set_temp":170,"time_set":0,"keepwarm":0,"smoke":0,"step_num":1,"set_temp":425,"use_timer":0}]},{"cycle_name":"Beginner\'s Brisket","populated":1,"num_steps":2,"units":1,"slot_num":1,"steps":[{"probe_set_temp":0,"time_set":12600,"keepwarm":0,"smoke":1,"step_num":1,"set_temp":165,"use_timer":1},{"probe_set_temp":190,"time_set":0,"keepwarm":0,"smoke":0,"step_num":2,"set_temp":225,"use_timer":0}]},{"slot_num":2,"populated":0},{"slot_num":3,"populated":0},{"slot_num":4,"populated":0}]},"details":{"thingName":"xxxxxx","userId":"xxxxxxxxxxxxxx","lastConnectedOn":xxxxxxxx,"thingNameLower":"xxxxxxxxxx","friendlyName":"bit e.me","lat":1111,"long":1111"deviceType":"xxxxxx"},"stateIndex":xxxxx,"schemaVersion":"xx"}'

```

## Describe the bug
After about 6-7 hours the MQTT Server stops responding to the Client MQTT "Connect" message.

## Debug log

Normal Operation:
```text
2021-12-xx 21:28:28 DEBUG (MainThread) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending DISCONNECT
2021-12-xx 21:28:30 DEBUG (MainThread) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2021-12-xx 21:28:30 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Received CONNACK (0, 0)
2021-12-xx 21:28:30 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending SUBSCRIBE (d0, m1) [(b'prod/thing/update/xxxxxxxxxx', 1)]
```

Failed Operation:
```text
2021-12-xx 22:28:29 DEBUG (MainThread) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending DISCONNECT
2021-12-xx 22:28:31 DEBUG (MainThread) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2021-12-xx 22:28:32 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2021-12-xx 22:28:34 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2021-12-xx 22:28:39 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2021-12-xx 22:28:47 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2021-12-xx 22:29:04 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2021-12-xx 22:29:36 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2021-12-xx 22:30:40 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2021-12-xx 22:32:41 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2021-12-xx 22:34:41 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Connection failed, retrying
2021-12-xx 22:36:42 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Connection failed, retrying
```

## Further Comments
-A simple reboot seems to resolve the connection for another 6-7 hours.
-The AWS-SDK keepalive default is 1200sec. We are currently running 60.
-The amount of Connect Attempts is based on `reconnect_delay_set` and currently defaulted @ 7.
-Based on the "AWS Traeger Success" article they are guestimating per grill cost @ $0.50 per grill. This integration polling and pinging every minute and continuing connections is eventually going to get noticed which may be the case here. What can we do to minimize this risk?

## Possible Action Items:
1. Change Keep Alive to 20min.
2. Add `reconnect_delay_set(min_delay=10, max_delay=160)` to decrease default re-attempts.
3. Add Logging to catch this error in HA.
4. Change the integration to default the `Connect Switch` back to state=off after startup.

@sebirdman are you having the same issue?

**Comment by sebirdman** [comment]
I've not seen this on my own setup, but i think it's likely that we could optimize with the action items you're suggesting anyways. 

>  -Based on the "AWS Traeger Success" article they are guestimating per grill cost @ $0.50 per grill. This integration polling and pinging every minute and continuing connections is eventually going to get noticed which may be the case here. What can we do to minimize this risk?

Where are we polling and pinging every minute? We should only be getting the device state after we subscribe to topics, then we just sit and wait for any updates from the grill to be pushed to us over the mqtt connection.

**Comment by njobrien1006** [comment]
Slight correction. We are not polling. Just pinging to validate the MQTT is still connected. Which would be 1440 pings/day. Also, we aren't pinging in the integration the MQTT_Client is.

> 2021-12-29 11:58:34 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Sending PINGREQ
2021-12-29 11:58:34 DEBUG (Thread-6) [custom_components.traeger] MQTT Log Level: 16, MQTT Log BUF: Received PINGRESP

**Comment by sebirdman** [comment]
@njobrien1006 looks like that's no additional cost for Traeger: https://aws.amazon.com/iot-core/pricing/additional-details/

> Your device can ping as often as every 30s, with no charge for MQTT PINGREQ or PINGRESP messages.

**Comment by njobrien1006** [comment]
@sebirdman I'd still say the daily Client connection (x24) won't go unnoticed forever.

I did the changes that I had proposed on my fork. [https://github.com/njobrien1006/hass_traeger/tree/Connect-Updates](url)

Currently waiting to see if the original problem remains.

**Comment by njobrien1006** [comment]
- My original testing for auto-disconnect, pinging changes, etc failed. Continued troubleshooting led me to another integration that uses socket-server/127.0.0.1 & 0.0.0.0.....once the other integration disabled the issue went away. Digging into Paho-Python led me to mqtt-client.Connect(bind_address). Fixing my bind address to my HA IP seemed to keep the connection indefinitely. Switching to 0.0.0.0 ended up failing within 24 hours. 

The phrase 
`If supplied, source_address must be a 2-tuple (host, port) for the socket to bind to as its source address before connecting. If host or port are ‘’ or 0 respectively the OS default behavior will be used.` in the socket documentation makes me believe the default OS behavior may be switching between incorrect internet inaccessible connections.

Still testing.....just an update.

**Comment by njobrien1006** [comment]
After months of graying hair and continuing to circle back to another integration, I've come to the conclusion that this issue isn't really related to this integration but seems to effect it somehow.

I reverted the other integration and haven't any issues since. Through the testing, I did find a couple worthy changes presented in #38.
