### ISSUE TITLE
cannot sign in?

### ISSUE THREAD

**Issue by k-rock** [sebirdman/hass_traeger#36]
Hi - I am trying to add this in my HA. Unfortunately, I am not able to add it with my (correct) username & password.

![image](https://user-images.githubusercontent.com/15674791/158879000-970bbac7-7d50-4d83-b47f-d26fbab4b711.png)

**Comment by njobrien1006** [comment]
Are you able to sign in and see your grill from the APP?
Username = email

I just signed in like you and didn't have any issues. Anything to show from the logs? If not, enable debug: 

> logger:
logs:  #debug/info/warning/error/critical
custom_components.traeger: debug

and see if anything shows then.

**Comment by k-rock** [comment]
My bad I think 
I updated my password and it works 
Thanks for your help

**Comment by njobrien1006** [comment]
No problem. Please mark the issue closed if resolved.

**Comment by sebirdman** [comment]
looks like this one is resolved

**Comment by NuAlex** [comment]
Just for the record, I was also having this issue to I logged-out and signed back in to confirm that the password was correct. Then I tried with my email username in all lowercase and it worked!
