### ISSUE TITLE
Do something with system_status

### ISSUE THREAD

**Issue by sebirdman** [sebirdman/hass_traeger#4]
just leaving this here for notes:

system_status 5: preheating
system_status 6: heated

**Comment by stephenpapierski** [comment]
I'll add these to the list.

- state["system_status"] == 8:  # Cool Down
- state["system_status"] == 7:  # Custom Cook
- state["system_status"] == 6:  # Manual Cook
- state["system_status"] == 5:  # Preheating
- state["system_status"] == 4:  # Igniting
- state["system_status"] == 3:  # Idle (Power switch on, screen on)
- state["system_status"] == 2:  # Sleeping (Power switch on, screen off)

**Comment by sebirdman** [comment]
we do stuff with system status now!
