### ISSUE TITLE
NumberEntity is not valid and will be unsupported from Home Assistant 2022.10

### ISSUE THREAD

**Issue by onedr0p** [sebirdman/hass_traeger#52]
## Debug log

```text

2022-07-09 12:00:03 WARNING (MainThread) [homeassistant.components.number] custom_components.traeger.number::TraegerNumberEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

```

**Comment by stephenpapierski** [comment]
Looks like the NumberEntity was refactored, and we need to update the properties we're setting to match the new setup. Doesn't look like too hard of a fix.

[Blog post on the refactor](https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring/)
[New Number Entity documentation we need to match](https://developers.home-assistant.io/docs/core/entity/number/)

**Comment by onedr0p** [comment]
If you still use this integration it would be great to see it updated. Thanks @stephenpapierski

**Comment by jbarbash** [comment]
Agreed, i'd love to see this fixed.

**Comment by stephenpapierski** [comment]
372a80fdc114edbae7b42eece55e617a7fcdda92 should fix the issue, but @sebirdman will have to cut a new release before an update shows in home assistant.

**Comment by onedr0p** [comment]
Any update on a release being cut @sebirdman ?

**Comment by stephenpapierski** [comment]
I think @sebirdman may be done developing on this project. @njobrien1006 has been actively developing over at https://github.com/njobrien1006/hass_traeger.

**Comment by onedr0p** [comment]
Good to know a fork lives on, I'll close this issue.
