### ISSUE TITLE
Climate versus water heater

### ISSUE THREAD

**Issue by stephenpapierski** [sebirdman/hass_traeger#6]
This is more of a question than a request, but is there a reason the water_heater entity was chosen instead of a climate entity? The built-in Lovelace thermostat card works great for climate entities, but to my knowledge there aren't any built-in cards for the water_heater element. At first glance, it seems that the climate entity supports everything necessary. I'm also willing to take a look and work on the code myself if this change makes sense.

**Is your feature request related to a problem? Please describe.**
Built-in cards don't support water_heater.

**Describe the solution you'd like**
A climate entity instead of a water_heater entity.

**Describe alternatives you've considered**
I've looked at the custom simple-thermostat card which supports water_heaters, but it's definitely more work that the thermostat card, especially if there isn't a strong reason for choosing the water_heater entity.

**Comment by sebirdman** [comment]
Hi @stephenpapierski 

I've actually considered doing this as well. it seems like a better option. The reason i chose water heater is actually because another project i'm using for my ge oven also chose that. 

I'd be curious to see how the climate entity works out instead.

**Comment by stephenpapierski** [comment]
#7

**Comment by sebirdman** [comment]
merged, next release will have that
