### ISSUE TITLE
Would it be possible to get the PR's merged in and a release created?

### ISSUE THREAD

**Issue by W0GER** [sebirdman/hass_traeger#60]
Looks like the last release here was over a year ago. Since then it looks like 3 new PR's have been submitted. Would it be possible to get these merged in and a release created? 

If this project is abandoned, what's the best way to keep this project moving forward?

**Comment by barryhaertel** [comment]
I have created a new fork and am interested in helping keeping this project moving forward https://github.com/systemswizard/hass_traeger-wifire

**Comment by rynop** [comment]
@systemswizard is your fork private?  Link 404s for me. I’m willing to help contribute

**Comment by dandomin** [comment]
Anyone have any luck on this question? Very interested in getting bluetooth probes exposed in HA.

**Comment by njobrien1006** [comment]
I've been working on my fork to address the request and continue development njobrien1006#53 & [2023.06.12-Beta](https://github.com/njobrien1006/hass_traeger/releases/tag/2023.06.12)

**Comment by rossc719g** [comment]
Has there been a decision on the future of this integration?

I have been working on trying to get the timers to be more friendly in the UI (https://github.com/rianadon/timer-bar-card/issues/132), and hit some issues that I can work around with template magic.. but the "real" solution would need to be addressed here.

But I really don't want to dogpile on with new issues for an integration that is "between maintainers".

So... The peasants want to know... do we have a new king of traeger?  :-)
(I am the peasants)

**Comment by njobrien1006** [comment]
I don't know the status of this main fork. I've continued development and maintenance releases in my fork.

I kind of already did what you are after here:

https://github.com/njobrien1006/hass_traeger/blob/master/config/www/epoch-clock-card/epoch-clock-card.js

**Comment by W0GER** [comment]
Closing issue as work seems to have moved to njobrien1006 fork.
