### ISSUE TITLE
Probe Temperature not displaying

### ISSUE THREAD

**Issue by JayPKinger** [sebirdman/hass_traeger#64]
I recently swapped my Home Assistant install from a raspberry pi to a dedicated machine.

Initially, when I setup the integration the probe temperature wasnt there... but a few days later it popped up as a entity.

Ever since the switch, I havent been able to get the probe temp entity to register in Home Assistant.

**Comment by williamcwallis** [comment]
I have the same issue. I never had any issues with the probe entities when setting up the integration, but now I can't get them to appear. Frustrating as they're arguably the most important entities to have.

**Comment by Viss** [comment]
same here. the probe 'just stopped working' in home assistant. it says the integration doesnt provide it anymore

**Comment by njobrien1006** [comment]
Got any logs? Grill model? Everything else seems to come up just the probe is MIA?

The probes are funky how they are added after the initial calls. Also, newer grill have multiple probes and may not be supported as the MQTT response is not always known.

My fork had a merge for the multiple probe situation.

**Comment by Viss** [comment]
My grill is the timberline 850. it's only got one probe. After an HA update the intergration simply said "this entity is no longer provided by this integration" and all my graphs and cards for the probe started throwing errors as if the underlying entity had just vanished. I tried removing and reinstalling the integration, and now the probe just flatly doesnt even appear in the list of available entities.
<img width="1022" alt="image" src="https://github.com/sebirdman/hass_traeger/assets/1756255/3d125941-4c7e-4050-a467-f39c008ed3a8">


Happy to troubleshoot for you if you have pointers, or can give me some instruction on what you would like to see!

**Comment by njobrien1006** [comment]
If it broke after a HA update, I would suspect it is throwing some more verbose errors in the logs. There have been some things HA have been depreciating that are important.

You can enable debug logging for the integration and see what it has.

Or try my [fork](https://github.com/njobrien1006/hass_traeger) as it has those deprecations addressed.

**Comment by Viss** [comment]
I've removed the builtin integration and installed yours via hacs and the entities "just reappeared"

thanks man!

**Comment by MastrUsr** [comment]
> If it broke after a HA update, I would suspect it is throwing some more verbose errors in the logs. There have been some things HA have been depreciating that are important.
> 
> You can enable debug logging for the integration and see what it has.
> 
> Or try my [fork](https://github.com/njobrien1006/hass_traeger) as it has those deprecations addressed.



Thank you so much! :)

**Comment by patrickcollins12** [comment]
> If it broke after a HA update, I would suspect it is throwing some more verbose errors in the logs. There have been some things HA have been depreciating that are important.
> 
> You can enable debug logging for the integration and see what it has.
> 
> Or try my [fork](https://github.com/njobrien1006/hass_traeger) as it has those deprecations addressed.

thanks @njobrien1006 . Works for me. I'd appreciate if @JayPKinger would let this become the official integration since his is not working any more.

**Comment by jianyu-li** [comment]
downloading yours @njobrien1006 now! Thanks for your work
