### ISSUE TITLE
Pellet Sensor

### ISSUE THREAD

**Issue by teshiburu2020** [sebirdman/hass_traeger#8]
Hey, i was just wondering if you were able to get pellet sensor data with this as well? 

Would be a nice touch, late at night google assistant just chimes in "pellets at 20%" and pulses a light ;)

**Comment by sebirdman** [comment]
@teshiburu2020 i don't yet own the pellet sensor! I'm planning on getting one sometime. I'm sure it's possible. how does the pellet sensor connect to the traeger?

**Comment by teshiburu2020** [comment]
It has a dedicated port on the board, the info is presented to the traeger
app so would imagine it's available to you

**Comment by sebirdman** [comment]
If anyone has the pellet sensor,  any help here would be great!

**Comment by teshiburu2020** [comment]
My traeger arrives monday i can assist then if you told me what to do :)

**Comment by stephenpapierski** [comment]
There is a value in the status message that reports the percentage that should be pretty easy to grab. Mine is at 60% right now. `"status":{"pellet_level":60,...}`

**Comment by stephenpapierski** [comment]
Adding the pellet sensor wasn't too bad. Made another pull request (#9). It might need some additional checks if grills without pellet sensors don't have that field in the status message.

**Comment by sebirdman** [comment]
@stephenpapierski thanks for that MR! 

i've merged that change. grills without pellet sensors just show 0% available.
